# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 850))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.nbPlayers = QtWidgets.QSpinBox(self.centralwidget)
        self.nbPlayers.setGeometry(QtCore.QRect(190, 20, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbPlayers.sizePolicy().hasHeightForWidth())
        self.nbPlayers.setSizePolicy(sizePolicy)
        self.nbPlayers.setStyleSheet("")
        self.nbPlayers.setReadOnly(False)
        self.nbPlayers.setObjectName("nbPlayers")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(19, 20, 161, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.strategiesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.strategiesTable.setGeometry(QtCore.QRect(20, 70, 540, 330))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strategiesTable.sizePolicy().hasHeightForWidth())
        self.strategiesTable.setSizePolicy(sizePolicy)
        self.strategiesTable.setMinimumSize(QtCore.QSize(0, 0))
        self.strategiesTable.setAutoFillBackground(True)
        self.strategiesTable.setStyleSheet("")
        self.strategiesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.strategiesTable.setIconSize(QtCore.QSize(0, 0))
        self.strategiesTable.setObjectName("strategiesTable")
        self.strategiesTable.setColumnCount(0)
        self.strategiesTable.setRowCount(0)
        self.strategiesTable.horizontalHeader().setVisible(True)
        self.strategiesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.strategiesTable.verticalHeader().setVisible(False)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(190, 410, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateButton.sizePolicy().hasHeightForWidth())
        self.generateButton.setSizePolicy(sizePolicy)
        self.generateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateButton.setObjectName("generateButton")
        self.starterButton = QtWidgets.QPushButton(self.centralwidget)
        self.starterButton.setGeometry(QtCore.QRect(830, 410, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starterButton.sizePolicy().hasHeightForWidth())
        self.starterButton.setSizePolicy(sizePolicy)
        self.starterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.starterButton.setObjectName("starterButton")
        self.profilesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.profilesTable.setGeometry(QtCore.QRect(640, 70, 540, 330))
        self.profilesTable.setStyleSheet("")
        self.profilesTable.setObjectName("profilesTable")
        self.profilesTable.setColumnCount(0)
        self.profilesTable.setRowCount(0)
        self.profilesTable.verticalHeader().setVisible(False)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(510, 410, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 490, 581, 341))
        self.groupBox.setObjectName("groupBox")
        self.r1 = QtWidgets.QRadioButton(self.groupBox)
        self.r1.setGeometry(QtCore.QRect(10, 55, 211, 30))
        self.r1.setChecked(True)
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QRadioButton(self.groupBox)
        self.r2.setGeometry(QtCore.QRect(10, 95, 561, 30))
        self.r2.setObjectName("r2")
        self.r3 = QtWidgets.QRadioButton(self.groupBox)
        self.r3.setGeometry(QtCore.QRect(10, 135, 561, 30))
        self.r3.setObjectName("r3")
        self.r4 = QtWidgets.QRadioButton(self.groupBox)
        self.r4.setGeometry(QtCore.QRect(10, 175, 261, 30))
        self.r4.setObjectName("r4")
        self.r5 = QtWidgets.QRadioButton(self.groupBox)
        self.r5.setGeometry(QtCore.QRect(10, 215, 281, 30))
        self.r5.setObjectName("r5")
        self.r6 = QtWidgets.QRadioButton(self.groupBox)
        self.r6.setGeometry(QtCore.QRect(10, 255, 551, 30))
        self.r6.setObjectName("r6")
        self.r7 = QtWidgets.QRadioButton(self.groupBox)
        self.r7.setGeometry(QtCore.QRect(10, 295, 551, 30))
        self.r7.setObjectName("r7")
        self.playersCombo = QtWidgets.QComboBox(self.groupBox)
        self.playersCombo.setGeometry(QtCore.QRect(400, 10, 171, 40))
        self.playersCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playersCombo.setObjectName("playersCombo")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(350, 20, 31, 21))
        self.label_2.setObjectName("label_2")
        self.results = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(640, 500, 540, 330))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results.sizePolicy().hasHeightForWidth())
        self.results.setSizePolicy(sizePolicy)
        self.results.setMaximumSize(QtCore.QSize(797, 591))
        self.results.setReadOnly(True)
        self.results.setObjectName("results")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pure Strategies"))
        self.label.setText(_translate("MainWindow", "Players number :"))
        self.generateButton.setText(_translate("MainWindow", "Generate Profiles"))
        self.starterButton.setText(_translate("MainWindow", "Start Game"))
        self.resetButton.setText(_translate("MainWindow", "Reset Game"))
        self.groupBox.setTitle(_translate("MainWindow", "Results to view"))
        self.r1.setText(_translate("MainWindow", "Nash Equilibriums"))
        self.r2.setText(_translate("MainWindow", "Strictly Dominant Strategies"))
        self.r3.setText(_translate("MainWindow", "Weakly Dominant Strategies"))
        self.r4.setText(_translate("MainWindow", "Pareto Optimality"))
        self.r5.setText(_translate("MainWindow", "Security Level"))
        self.r6.setText(_translate("MainWindow", "Iterative Elimination Of Strictly Dominated Strategies"))
        self.r7.setText(_translate("MainWindow", "Iterative Elimination Of Weakly Dominated Strategies"))
        self.label_2.setText(_translate("MainWindow", "Of :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

